cockroachdb/cockroach-operator

- .gitignore
- Makefile
- e2e/testdata/TestCreatesInsecureCluster/creates_1-node_insecure_cluster.golden
- e2e/testdata/TestCreatesSecureClusterWithGeneratedCert/creates_1-node_secure_cluster.golden
- hack/apply-operator.sh
- hack/create-gke-cluster.sh
- pkg/testutil/assert.go
Often annotations are added to pods by other sources. When
testing with gke with network policies enabled the unit tests are
failing because annotations are added by Calico. I am removing
those annotations in this test.
I have some updates to the Makefile as well.
CLOSES ISSUE: https://github.com/cockroachdb/cockroach-operator/issues/45
> Updating e2e test to remove annotations in GKE

- README.md
For first time users, it's not intuitive that persistent volumes and persistent volume claims are not deleted when the CockroachDB cluster is deleted from Kubernetes. This additional comment clarifies how to manually remove persistent volumes and persistent volume claims.
cc @chrislovecnm
> updated README - additional comments, deleting pv and pvc

- pkg/resource/pod_distruption_budget.go
- pkg/resource/pod_distruption_budget_test.go
And this is why we need CI.  I missed headers on two new
go files.
> Missed headers on go files

- e2e/testdata/TestCreatesInsecureCluster/creates_3-node_insecure_cluster.golden
- e2e/testdata/TestCreatesSecureClusterWithGeneratedCert/creates_1-node_cluster.golden
- e2e/testdata/TestCreatesSecureClusterWithGeneratedCert/creates_1-node_secure_cluster.golden
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
By default Kubernetes mounts the default API authentication
token to a Pod.  This PR adds 'automountServiceAccountToken: false'
to the StatefulSet definition for a managed database.
Closes #66
> Stop auto-mounting SA Token

- pkg/resource/statefulset.go
- pkg/resource/statefulset_test.go
The statefulset builder now checks if the environment variable
RELATED_IMAGE_COCKROACH is set.  If RELATED_IMAGE_COCKROACH is
set the container image is set to that value instead of the
value set in the CR. RedHat testing sets this ENV variable
to test a specific image from a specific container registry.
> RedHat testing image name override

- Makefile
- e2e/BUILD.bazel
- e2e/e2e_test.go
- e2e/testdata/TestCreatesInsecureCluster/creates_3-node_insecure_cluster.golden
- e2e/testdata/TestCreatesSecureClusterWithGeneratedCert/creates_1-node_secure_cluster.golden
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- pkg/testutil/paths/paths.go
We previously allowed for gke testing during e2e, but
we are going to use kind.  This removes a couple of YAML
stanzas in the test data that kind does not produce.
> Changing e2e testing to use kind

- e2e/testdata/TestCreatesInsecureCluster/creates_3-node_insecure_cluster.golden
- e2e/testdata/TestCreatesSecureClusterWithGeneratedCert/creates_1-node_secure_cluster.golden
- pkg/actor/initialize.go
- pkg/resource/cluster.go
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
This is a cleanup and general change of how we are starting the
CR Pods, and also how we are createing the advertise-host option.
Moreover we are not using a shell command, but are directly running
the coachroach command.  This change is required due to the fact
that the ubi redhat container does not have the hostname command.
> Updating Command and Arguments for CR Pods

- Makefile
- e2e/e2e_test.go
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
1. Added  dev/syncdeps target on makefile
2. Rebuild and replace binaries for kubetest2 and kubetest2_kind
3. We still need core-utils for macos install because of the usage of realpath
> fix e2e tests for macos

- README.md
small nit in readme when running any command in built-in SQL client 
```
#
#
ERROR: cannot load certificates.
Check your certificate settings, set --certs-dir, or use --insecure for insecure clusters.
```
but works with `/cockroach/cockroach-certs`
> fix certs path in readme

- manifests/operator.yaml
quick manifest change to point at cockroach-operator in dockerhub
> point operator.yaml to dockerhub by default

- README.md
- examples/example.yaml
Fixes https://github.com/cockroachdb/cockroach-operator/issues/234. These settings were verified to work with `n1-standard-4`.
> update default resource values

- manifests/BUILD.bazel
We had a typo in BUILD.bazel file that did not allow k8s apply to work.
> Correcting typo for bazel

- README.md
Added known limitations from https://github.com/cockroachdb/docs/issues/9188 to the existing list.
@johnrk Is the persistent volume limitation still unresolved? It was previously on the list but not on the new list you created.
> add Operator limitations to README

- pkg/resource/job.go
- pkg/resource/statefulset.go
In order to not have the crdb run as PID 0 we are using the
shell script now.
> Using shellscript entrypoint

- cmd/cockroach-operator/main.go
- manifests/BUILD.bazel
- manifests/operator.yaml
- pkg/actor/BUILD.bazel
- pkg/actor/decommission.go
- pkg/actor/deploy.go
- pkg/actor/initialize.go
- pkg/actor/partitioned_update.go
- pkg/actor/request_cert.go
- pkg/actor/validate_version.go
- pkg/controller/BUILD.bazel
- pkg/controller/cluster_controller.go
- pkg/resource/job.go
- pkg/scale/BUILD.bazel
- pkg/scale/drainer.go
- pkg/scale/persistent_volume_pruner.go
- pkg/scale/scale.go
- pkg/update/BUILD.bazel
- pkg/update/update.go
- pkg/update/update_cockroach_version.go
- pkg/update/update_cockroach_version_common.go
This PR implement does two things.  First, we are now able to set the log level on the command line.  The operator now accepts the zap logging flags, and you can set the level to say "debug".  The operator framework uses the zap logging library and the best manner to implement logging, which I found was to use the zap library.  We will set the operator to "warn", but the zap library defaults to debug.
The second change is a general audit of which logging level is used for which logging statement.  Several changes were made to include "debug", "info", "warn", and other logs. 
Fixes: https://github.com/cockroachdb/cockroach-operator/issues/304
We need information on how to configure logging via the command line included in the documentation - @johnrk 
I may have missed a couple of logging …
> Logging changes for operator

- hack/bin/deps.bzl
I missed a path with downloading the crdb binary when running
OSX.  We should probably not have the rule the way it is, but it
is fine for now.
> Fixing crdb binary in OSX

- .bazelrc
- Makefile
- WORKSPACE
- e2e/BUILD.bazel
- e2e/assert.go
- e2e/e2e_test.go
- hack/BUILD.bazel
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- hack/gke/BUILD.bazel
- hack/gke/start_stop_gke.go
- manifests/BUILD.bazel
- manifests/substitute.sh
- pkg/testutil/exec/BUILD.bazel
- pkg/testutil/exec/exec.go
- updated docker bazel rules
- updated k8s bazel rules
- added a script to edit the manifest on the fly so that bazel works
- improving the capability to run GKE
- added make targets
- tested on GKE
- modified e2e testing to not start a cluster automatically
- modified e2e testing to accept a parameter for testing pvc resizing
- updated the kubetest2 builds in gcp
Once we have this in we will need to have the infra team have gcloud and the correct GCP permissions on the teamcity server in order to use this functionality on a nightly build.
TODO
> Getting GKE E2E running and Bazel updates

- cmd/cockroach-operator/BUILD.bazel
This PR allows a user to build the container on OSX and still
embed the linux crdb binary into the operator container.
> Adding Linux CRDB Binary for Container

- .github/workflows/ci.yaml
- Makefile
The patch reflects the CI builds we have in TeamCity.
* Run against bazel 3.7.2 and 4.0.0
It will be running in parallel with TeamCity for now and won't be blocking merges. We can make it mandatory after we decide in #363
> Add GitHub Actions support

- DEVELOPER.md
- Makefile
- WORKSPACE
- hack/build/print-workspace-status.sh
This PR addresses the updating of --stamp variables
via moving the stamp variables to "STABLE" values.
Moving the values to "STABLE" seems to force the updating
of rules_k8s files better.
Secondly, since this is working I fixed applying the GKE manifest
during the e2e cluster.
Lastly I added setting a missing environment variable to the apply
commands when running rules_k8s bazel commands.
> Fixing K8S Cluster Stamping

- .github/workflows/ci.yaml
Bazel 4.0.0 is working just fine, no need to have both bazel 3
and bazel 4 run with e2e.
> Removing Bazel 3

- cmd/cockroach-operator/BUILD.bazel
Building a tar layer from running YUM update commands
using the UBI image. We now use that tar ball as part
of the package.
> Updating UBI image with yum commands

- cmd/cockroach-operator/BUILD.bazel
After the v1.7.0 was submitted to RedHat Connect, the image failed the
`free_of_important_vulnerabilities`.
According to the
[container_run_and_commit_layer](https://github.com/bazelbuild/rules_docker/blob/8c3a8110a0c519929a7e79c39ac345a0f8c74d04/docker/util/README.md#container_run_and_commit_layer)
documentation, the output should be used in the `layers` attribute.
> Specify ":ubi_update" as a layer

- Makefile
When the `release/image` target is run multiple times, it doesn't
refresh the base RedHat UBI image. As a result we may end up with an
image without security updates.
This change ensures that we run `bazel clean --expunge` for the release
target.
> Clean up bazel cache for release builds

- cmd/cockroach-operator/BUILD.bazel
The current command doesn't update the image to the state when it passes
the RedHat Connect checks.
> Update all ubi packages

- apis/v1alpha1/cluster_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- config/rbac/role.yaml
- manifests/operator.yaml
- pkg/actor/BUILD.bazel
- pkg/actor/actor.go
- pkg/actor/deploy.go
- pkg/actor/deploy_test.go
- pkg/controller/cluster_controller.go
- pkg/kube/BUILD.bazel
- pkg/kube/kubernetes_distro.go
- pkg/resource/statefulset.go
- pkg/resource/statefulset_test.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
This PR does three things.
1. Any env prefixed with CRDB that is in the operator is now
passed into the pods.
2. Telemetry now adds the dynamic value of the k8s distro that
it is running on.
3. Adds a new CRD field that allows the user to set one of more Pod environment variables.
> Capability to set environment variables and telemetry

- examples/client-secure-operator.yaml
Add YAML for a secure client pod. Verified with @keith-mcclellan and tested that this works.
This will be used in documentation steps.
Relates to https://github.com/cockroachdb/docs/issues/8889
> add secure client pod yaml

- e2e/e2e_test.go
The TestUpgradesMinorVersion/upgrades_the_cluster_to_the_next_patch_version
has been flakey, and I am doing two things to attempt to fix it.
1. Increase timeouts
2. Using newer version of CR
> Updating e2e test to use newer values

- pkg/resource/BUILD.bazel
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
1. Dynamically set cache and max sql memory if the user does
not set a CRD value
2. sts is set to Parallel pod management
We are making changes to use `exec` and bash directly in order to
start the Pods and set the cache values dynamically.  We are also
adding environment variables in to the Pods that set the GOPROCSMAX
and also MEMORY_LIMIT_MIB which is used to set CR cachee and
max sql memory values.
> StatefulSet Changes - CR Cache, Memory, and sts pod management

- pkg/actor/actor.go
Decommission needs to run before other actors
This should resolve the issues we are seeing on https://github.com/cockroachdb/cockroach-operator/issues/473
> Update actor order to run decommission first

- pkg/testutil/env/BUILD.bazel
- pkg/testutil/env/sandbox.go
This PR creates the RBAC bindings that are required to run e2e testing
with openshift. We are creating the role binding and role that
allows the operator database service account to a Pod as any UID.
When the e2e test starts the role is created, and when the test
is over the role is destroyed.  This code stop e2e testing
to occur in parallel. But we have other problems with parallel testing
as well.
> Creating RBAC objects for Openshift E2E

- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
Adding the drain PreStop Hook for CRDB.
Removed LivenessProbe probe due to problems when pods are resource constrained.
> Adding PreStop Hook - Removing LivenessProbe

- BUILD.bazel
- e2e/create/BUILD.bazel
- e2e/decomission/BUILD.bazel
- e2e/decomission/decomission_test.go
- e2e/pvcresize/BUILD.bazel
- e2e/upgrades/BUILD.bazel
- pkg/actor/BUILD.bazel
- pkg/actor/decommission.go
- pkg/actor/decommission_test.go
- pkg/features/operator_features.go
We are having issues with the Decommission Actor so we are turning
it off by default.  You can enable the Actor via the feature flag.
The test case for this PR is that Decommission will run when we enable the flag.  Otherwise, it will not run.
> Shutting off Decommission Actor by default

- pkg/testutil/require.go
In the e2e tests for decommission we used the index of the pod to check the replicas of the decommissioned nodes. 
Since we are using Pod Parallel Strategy the index of the pod and the  id are not the same anymore, so now I am filtering using the address that contains the host of the last node that was decommissioned to get the replicas.
> fix decommision e2e test to use host

- pkg/actor/BUILD.bazel
- pkg/actor/actor_test.go
The slice that is returned by NewOperatorActions drives
the order of actors working on a CRD. This order
is INCREDIBLY important for the operator, so this test
ensures the order is not changed accidentally.
> Unit test for testing actor order

- pkg/update/BUILD.bazel
- pkg/update/update.go
The intial update of the sts returned that we cannot update the
sts since the sts is newer.  We then get the sts again and retry to
update it again.
> Retrying if we have a conflict with an update

- e2e/decomission/decomission_test.go
- pkg/actor/decommission_test.go
- pkg/features/operator_features.go
- enabled deco via changing feature gate
- changed unit test, to test that it is enabled
- updated operator_features comments
- moved prune pvc to alpha
- we have two e2e tests, one that prunes PVCs and another that
does not prune pvcs.
> Enabling Decommission

- pkg/scale/scale.go
This is a fix for #619 when the initial feature flag went in we guarded only against the initial PVC prune and not the final prune.
> Add missing feature flag guard

- Makefile
Previously, we hardcoded the `CHANNEL` and `IS_DEFAULT_CHANNEL` variables
in Makefile for the `release/gen-files` target in order to reduce the
possibility of publishing a release to a wrong channel.
Now, that we have these steps documented and automated, we can remove
the hardcoded variables. By default, they will be set to `CHANNEL=beta`
and `IS_DEFAULT_CHANNEL=0`. The release docs will explicitly override
these variables.
> Do not override `CHANNEL` and `IS_DEFAULT_CHANNEL`

- e2e/decomission/decomission_test.go
- pkg/testutil/require.go
Added a check to make sure the PVC's are deleted or kept as expected. Also changed the decommission test cases to use the namespace. It was causing some requests like for PVCs to select across all namespaces and was finding extras. [cluster.Namespace()](https://github.com/cockroachdb/cockroach-operator/blob/master/pkg/testutil/require.go#L516) was always `nil`. We might want to check if this is causing issues in other testacases as well.
> Add pvc check to decommission

- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
Fixing bug where the operator was adding the initcontainer
when TLS was disabled.
> Removing initcontainer when TLS is disabled

- Makefile
- e2e/kubetest2-openshift/README.md
With #651 merged, we can disable service account and service operations.
In order to do this, we would need to change the TeamCity configuration
and pass `--do-not-enable-services=true --do-not-delete-sa=true` as
`EXTRA_KUBETEST2_PARAMS`.
> Add ability to pass extra params to openshift

- .github/workflows/update-crdb-versions.yaml
- hack/update-crdb-versions.sh
Previously, we had to manually track CRDB releases and update the
corresponding file in this repo.
This patch uses the RedHat Catalog API to fetch all published CRDB
images and regenerate the `crdb-versions.yaml` file. If the file is
changed, the GitHub action would create a PR.
Example PR: https://github.com/rail/cockroach-operator/pull/3
> Add GitHub action to update CRDB versions

- BUILD.bazel
- Makefile
- e2e/kubetest2-eks/BUILD.bazel
- e2e/kubetest2-eks/deployer/BUILD.bazel
- e2e/kubetest2-eks/deployer/build.go
- e2e/kubetest2-eks/deployer/deployer.go
- e2e/kubetest2-eks/deployer/down.go
- e2e/kubetest2-eks/deployer/dumplogs.go
- e2e/kubetest2-eks/deployer/up.go
- e2e/kubetest2-eks/main.go
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- hack/eks-storageclass.yaml
Using aws-k8s-tester and kubetest2 to create an eks cluster,
run the e2e tests and then tear down the cluster.
> Implementing kubetest2-eks

- go.mod
- go.sum
- hack/build/repos.bzl
- pkg/clustersql/BUILD.bazel
- pkg/clustersql/settings.go
- pkg/clustersql/settings_test.go
- pkg/clustersql/zones.go
- pkg/clustersql/zones_test.go
- pkg/update/BUILD.bazel
- pkg/update/update_cockroach_version.go
Adding tests for the `clustersql` package. This involved some very light refactoring and removing some duplicate code in _pkg/update_ which has been updated to use `SetClusterSetting` and `GetClusterSetting` from the `clustersql` package now.
> Add tests for clustersql package

- BUILD.bazel
- go.mod
- go.sum
- pkg/kuberecord/BUILD.bazel
- pkg/kuberecord/cassettes.go
- pkg/kuberecord/cassettes_test.go
- pkg/kuberecord/mode.go
- pkg/kuberecord/mode_test.go
- pkg/kuberecord/recorder.go
- pkg/kuberecord/recorder_test.go
- pkg/kuberecord/testdata/cassettes/kuberecord_demo.vcr.yaml
- pkg/testutil/BUILD.bazel
- pkg/testutil/env.go
- pkg/testutil/env/BUILD.bazel
- pkg/testutil/env/path_test.go
- pkg/testutil/env_test.go
- pkg/testutil/validate_headers_test.go
__**NOTE**: I know +1600 looks scary, but over 900 lines are for the YAML fixture__
Adding `kuberecord` which is a package that leverages the [go-vcr](https://github.com/dnaeon/go-vcr) to record interactions with a K8s API server.
This is useful to avoid having to run every command over and over again when running tests. In theory, unless the API version changes, we typically don't expect the behaviour to be any different for things like CreateNamespace, ListPods, etc.
Kuberecord works by wrapping the incoming rest.Config to handle loading prerecorded interactions, scrubbing sensitive/flakey headers, and storing results to disk (`./testdata/<name>.vcr` by default).
This code is largely "borrowed" from an internal repo where it has been in use for a while already. In order to keep the diff …
> Add kuberecord to enable VCR for K8s API calls

- apis/v1alpha1/cluster_types.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
Fixes #668
There are a couple of places where we've got `+required` markers on struct fields, but have `omitempty` in the JSON tag. Similarly we've got a few mismatched `+optional` and `(Required)` text in the comments (see #668 for an example).
This patch addresses those and standardizes on the following format for field level comments in the api types:
```
[(Optional)] <description>
[Default: <val>]
[other markers]
[+optional|+required]
```
I ran `make dev/generate` after making these changes to ensure the generated code was up to date.
> Updating markers for cluster types

- apis/v1alpha1/cluster_types.go
- apis/v1alpha1/cluster_types_test.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- pkg/actor/decommission.go
We currently check for the node count to be >=3 in the decommissioner. There's actually a `TODO` comment in there about adding a validation hook to avoid this. However, since the admission controller will always run the OpenAPI validation when resources are submitted to the API server, we don't actually need a hook for this.
I've added a minimum=3 marker to the spec, which will be enforced automatically, negating the need for this check.
**Proof:**
To try this out, you can update the `nodes` property in `examples/example.yaml` to be `2`. The run the following:
```
make dev/up && make dev/up-wait # start a local kind cluster
kubectl apply -f examples/example.yaml
=> The CrdbCluster "cockroachdb" is invalid: spec.nodes: Invalid value: 2: spec.nodes in body should be greater than or equal to …
```
> Use OpenAPI validation for node count

- apis/v1alpha1/cluster_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- pkg/kube/helpers.go
- pkg/resource/discovery_service.go
- pkg/resource/discovery_service_test.go
- pkg/resource/job.go
- pkg/resource/pod_distruption_budget.go
- pkg/resource/pod_distruption_budget_test.go
- pkg/resource/public_service.go
- pkg/resource/public_service_test.go
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args_in.yaml
- pkg/testutil/builder.go
Closes #696 
* Added Custom Annotations support in crdb cluster
* Added the new API field "additionalAnnotations" for adding user defined annotations to CRDB cluster resources
* Added/Modified existing unit test for this change
> Added Custom Annotations support in crdb cluster #696

- WORKSPACE
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
Some of our build dependencies were getting quite old, and some were no longer needed. I went through each one and verified first if it was needed, then updated it when necessary.
**EDIT:** I initially intended to bump the build deps, then follow up with a PR for normal runtime deps. However, some of the build dependency updates require updated runtime dependencies. For example, bumping etcd to 3.5.0 requires an updated version of controller-runtime (which in turn requires an updated version of client-go). So I've updated the strictly necessary runtime deps here as well.
> Bump build dependencies

- pkg/actor/deploy.go
- pkg/resource/discovery_service.go
- pkg/resource/job.go
- pkg/resource/pod_distruption_budget.go
- pkg/resource/public_service.go
- pkg/resource/resource.go
- pkg/resource/statefulset.go
Related to https://github.com/cockroachdb/cockroach-operator/pull/714#discussion_r712474193
There's an unnecessary check for the node counts here in the deploy action. This is handled automatically by the admission controller since we've got a validation on the minimum node count (3).
While I was here, I also updated the action to loop through all the builders (in order) to avoid duplicating all of the reconciler and error checking code.
> Drop Nodes() check and loop through builders in deploy action

- pkg/controller/cluster_controller.go
- pkg/controller/result.go
I'm doing an audit of the way the actors handle errors, and as part of that, looked into how reconciliation handles the errors. It doesn't really make sense that a "permanent" error should get ever get requeued, so let's make them not requeue.
The two existing uses of PermanentErr are indeed pretty permanent: both occur when the `cockroach version` command doesn't run successfully.
> don't requeue permanent errors

- apis/v1alpha1/volume.go
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
Our intention with `AdditionalLabels` is to add them to all resources created by CrdbCluster. Currently, the PVCs are missing these. So I've updated the StatefulSet resource appropriately to add the labels.
How to verify this works:
```shell
$ make dev/up
$ kubectl apply -f examples/example.yaml
$ kubectl get pods -w # wait until at least one of the db pods is running and ready
$ k get pvc datadir-cockroachdb-0 -oyaml
$ make dev/down
```
> Add labels to PVCs

- cmd/cockroach-operator/prep_webhooks.go
- pkg/resource/webhook_secret.go
- pkg/resource/webhook_secret_test.go
This passes the namespace of the operator to the DNS names used in the webhook TLS certificate.
Fixes #725
> Add correct namespace to generated webhook cert

- e2e/create/create_test.go
- e2e/decomission/decomission_test.go
- e2e/pvcresize/pvcresize_test.go
- e2e/upgrades/upgrades_test.go
- e2e/upgradessha256/upgradessha256_test.go
- e2e/versionchecker/versionchecker_test.go
- pkg/testutil/env/env.go
There's an issue with the existing test structure where the controller may log something in between when a test finishes and when the test env is torn down, causing a panic. I'm working on a separate PR that adds some more logging to the controller and this race condition became really apparent.
Fix by starting and stopping the test env tightly around each test.
> Tear down test env with each test

- .github/workflows/e2e-kind-upgradessha256.yaml
The e2e upgradessha256 job had the same name as the e2e upgrades job in CI, and because of that I think they ended up running the exact same tests which is a little pointless. I think this fixes it to what was intended.
> make upgradessha256 actually run upgradessha256

- apis/v1alpha1/condition_types.go
- pkg/actor/actor.go
- pkg/actor/actor_test.go
- pkg/actor/initialize.go
- pkg/condition/condition.go
It looks like the intent of this one existing line in Initialize is to actually set the cluster initialized condition to true, but currently it's only working by coincidence when the updated cluster gets written way downstream for something unrelated. The bit of refactoring I've done so far has surfaced this bug.
Make it so we actually update the cluster initialized condition within the initialize actor.
> actually update cluster conditions in initialize actor

- pkg/controller/BUILD.bazel
- pkg/controller/cluster_controller.go
I just ran into another bug in e2e testing where the version checker job started and then...absolutely nothing happened and the test timed out:
```
logger.go:130: 2021-09-29T19:58:00.059Z	INFO	reconciling CockroachDB cluster	{"CrdbCluster": "crdb-test-m9g4jp/crdb", "ReconcileId": "Hq3Y3Q4sDNRVqepTBWDWYK"}
logger.go:130: 2021-09-29T19:58:00.059Z	INFO	Running action with name: VersionCheckerAction	{"CrdbCluster": "crdb-test-m9g4jp/crdb", "ReconcileId": "Hq3Y3Q4sDNRVqepTBWDWYK"}
logger.go:130: 2021-09-29T19:58:00.059Z	WARN	starting to check the crdb version of the container provided	{"CrdbCluster": "crdb-test-m9g4jp/crdb", "ReconcileId": "Hq3Y3Q4sDNRVqepTBWDWYK"}
logger.go:130: 2021-09-29T19:58:00.059Z	WARN	User set image.name, using that field instead of cockroachDBVersion	{"CrdbCluster": …
```
> Make the controller watch Job objects

- .github/pull_request_template.md
- CHANGELOG.md
- hack/release/main.go
- hack/release/steps.go
- hack/release/steps_test.go
The title says it all really. The format follows a known standard, and includes links to the diffs for every released version.
I've also updated hack/release to automatically convert the previous `[Unreleased]` section to the new release and add a new unlreleased heading to point to the diff between the latest release and master.
Finally, I went through the changes from v2.1.0 to now and backfilled the details here.
> NOTE: If we've got a previous beta, as we do right now, we'll need to copy the details (Added/Changed/etc) from those to the new release before pushing the new release branch.
New PRs will have a checklist that will remind us to update the changelog regularly.
**Testing**
To test this out, you need to comment out the `origin/master` argument in hack/release/steps.go since …
> Adding CHANGELOG.md for tracking changes between releases

- .github/workflows/e2e-kind-create.yaml
- .github/workflows/e2e-kind-decommission.yaml
- .github/workflows/e2e-kind-upgrades.yaml
- .github/workflows/e2e-kind-upgradessha256.yaml
- .github/workflows/e2e-kind-versionchecker.yaml
- .github/workflows/templates.yaml
- .github/workflows/tests.yaml
We recently ran into an issue where an update to README wouldn't run the required checks. It would make sense to skip the checks for docs changes, but the checks are required for merging. Leading us to change .gitignore simply to trigger them.
We can look into a better long-term solution, but for now I've altered the workflows to run on every push/pr to master.
**Checklist**
> Always run required checks

- .gitignore
- CHANGELOG.md
- cmd/cockroach-operator/main.go
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/manifests/patches/deployment_patch.yaml
- config/rbac/role.yaml
- config/templates/deployment_patch.yaml.in
- hack/update-pkg-manifest.sh
- install/operator.yaml
- pkg/controller/cluster_controller.go
Fixes #779
Fixes #780 
Fixes #784 
We have a couple of issues that prevent the operator from running properly on OpenShift.
**Issue 1: Webhooks**
The first has to do with webhook configuration. On startup, we generate a CA and associates TLS certificates for the webhook-service. The CA is patched into the webhook config's CABundle and the certs are placed on disk for the webhook service to use.
The trouble is that openShift doesn't name the webhook configurations the same (for the better IMO). So at startup we can't find the hook and bail on startup (CrashLoopBackoff).
OpenShift will setup the service and patch the CA bundle automatically, so I've added the `-skip-webhook-config` flag and ensured that it's set in the manifests for OpenShift by default.
**Issue 2: Jobs**
When we deploy a …
> Address issues with running on OpenShift

- CHANGELOG.md
- config/rbac/role.yaml
- install/operator.yaml
- pkg/controller/cluster_controller.go
When testing out  an upcomfing change to how we determine which actor to run, we noticed there were some error messages when scaling down (decommissioning) a cluster. The issue is that we aren't able to update the scale subresource for statefulsets.
I've added the permissions and verified that it works locally and in a GKE cluster.
**Checklist**
> Add sts/scale permissions for operator role

- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- hack/dev.sh
Added support for developer workflow on Mac m1. This PR allows you to run all bazel tests and locally spin up the cockroachdb operator environment on Mac m1 machine.
**Checklist**
> Support the mac m1 for development workflows

- hack/smoketest/main.go
- hack/smoketest/steps.go
- hack/smoketest/steps_test.go
Since updating the default namespace to `cockroach-operator-system` the nightly smoke tests have been failing. This is because there is a check to wait for a deployment (that doesn't exist) to be available.
This patch adds the namespace to the appropriate calls and makes the tests work again. I've verified this by running the following command locally: `make test/smoketest NODE_VERSION=1.22.1`
**Checklist**
> Update smoke tests to be aware of new namespace

- pkg/actor/validate_version.go
Added a check for checking the image section is nil or empty.
No need to check in version checker that either the name or image section should be provided. These check is already done in admission web hooks, hence either of one will be present.
> Fix the check of validate version for image name and cockroachdb version

- hack/k8s/verify_k8s_running.go
- pkg/testutil/env/env.go
Our nightly tests have been failing. At first, we thought it might just
be flakiness, but the issue appears to be consistent.
After running the tests from my local machine, I was able to reproduce
the issue and found that by adding a pause before saying K8s is ready, I
can reliably get the tests to pass.
Clearly, adding a sleep call is not ideal/desirable. I'm hoping to get
this in so we can stop the bleeding so to speak and then figure out what
the actual issue is.
> Give nightly tests a bit longer to be ready

- CHANGELOG.md
- e2e/decommission/decommission_test.go
- pkg/scale/drainer.go
- pkg/testutil/require.go
Currently, nodes are decommissioned by executing `cockroach node
decommission --wait=none` and then waiting for `replicas` to hit zero by
polling `cockroach node status --decommission`.
This leaves nodes in the _decommissioning_ state and never "finalizes"
the decommission by setting their state to decommissioned.
This PR adds a call to `cockroach node decommission` (without the `--wait` flag) once the replicas have
gone down to 0, which will mark the node as decommissioned
appropriately.
**Checklist**
> Properly mark nodes as decommissioned

- hack/bin/deps.bzl
I was having trouble creating a test cluster using the instructions in
openshift.md. Upgrading to a newer version resolved the issue.
**Checklist**
> Bump OpenShift depedencies to 4.9-stable

- cmd/cockroach-operator/BUILD.bazel
Our publish step for the docker image was failing since yum is now a
protected package in the ubi base image.
I've updated the script to leave yum, but clear its cache. The
resulting image results in a slightly smaller (184MB vs 193MB) image.
From the output logs:
```
error: Could not depsolve transaction; 1 problem detected: Problem: The
operation would result in removing the following protected packages: yum
```
I tested this locally, before and after the fix with:
```
bazel run //cmd/cockroach-operator:ubi_base_image -- --norun
```
> Update build steps to avoid removing yum

- CHANGELOG.md
- config/manager/patches/image.yaml
- config/templates/deployment_image.yaml.in
- install/operator.yaml
When supplying `cockroachDBVersion` in the spec rather than a specific
image, we check for the image in the manager's env. However, at the
moment that env doesn't include the related images.
This PR addresses that by adding them to the generated deployment
manifest, which in turn is used to create the operator.yaml file in
_/install_.
I've verified that everything still works as expected when generating
the bundle by running `make release/generate-bundle` and ensuring the
image values are what we expect.
**Checklist**
> Add RELEASE_IMAGE_COCKROACH_<version> to manager env

- CHANGELOG.md
- apis/v1alpha1/webhook.go
- apis/v1alpha1/webhook_test.go
This is an attempt to fix the issue reported
in https://github.com/cockroachdb/cockroach-operator/issues/850
and https://github.com/cockroachdb/cockroach-operator/issues/845.
Currently, there seems to be a bug in
[k8s-objectmaker](https://github.com/banzaicloud/k8s-objectmatcher/pull/49),
which causes the operator to think that the sts
has changed since creation and get stuck in the reconcilation loop.
To mitigate, we check whether `volumeMode` is set,
and set correctly upon cluster creation.
> Validate pvc.volumeMode to circumvent potential reconcilation loop

- CHANGELOG.md
- e2e/create/create_test.go
- pkg/actor/validate_version.go
This PR addresses issue #846.
Previously, using cockroachDBVersion unintentionally runs
some code that also leads to nil pointer panics.
This PR corrects this mistake.
> Short circuit version checker when cockroachDBVersion is set

- CHANGELOG.md
- pkg/resource/job.go
When `additionalAnnotations` is used, the pod created by the job doesn't contains any annotations.
The job resource is well annotated but not the pod created by this job.
Jobs description:
```
[root@b172fa08ae6d /]# kubectl describe jobs cockroachdb-vcheck-27429940
Name:           cockroachdb-vcheck-27429940
Namespace:      default
Selector:       controller-uid=338ec2fc-fe6f-4e3d-8199-4d58ef334b2d
Labels:         app.kubernetes.io/component=database
app.kubernetes.io/instance=cockroachdb
app.kubernetes.io/managed-by=cockroach-operator
app.kubernetes.io/name=cockroachdb
app.kubernetes.io/part-of=cockroachdb
crdb=is-cool
Annotations:    crdb.io/last-applied: XXXXXXX
my-additional-annotation: value_of_my_additional_annotation
Controlled By:  CrdbCluster/cockroachdb
Parallelism:    1 …
```
> Add Annotations to the pod created by the job

- CHANGELOG.md
- pkg/actor/validate_version.go
if the cluster contains security tools working as sidecar,
the GetLogs function requires to read "crdb" container only
Example of cockroach-operator error log, when a sidecar container is injected to the vcheck pod:
Error:
```
runtime.goexit
| src/runtime/asm_amd64.s:1581
Wraps: (2) error in opening stream
Wraps: (3) a container name must be specified for pod cockroachdb-vcheck-27429886-hqfnm, choose one of:
[XXXXXXXXXX-init-container XXXXXXXXXX-container crdb]
Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *errors.StatusError
```
StackTrace: 
```
github.com/cockroachdb/cockroach-operator/pkg/actor.(*versionChecker).Act
| \tpkg/actor/validate_version.go:219
| github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile
| …
```
> Add sidecar support

- pkg/resource/resource.go
during learning code of `reconcileAnnotations`, I think it should `SetAnnotations` when init desired object's annotations.
otherwise following put aa should be useless?
**Checklist**
> Fix reconcile annotations init when it's nil

- .github/workflows/e2e-kind-create.yaml
- .github/workflows/e2e-kind-decommission.yaml
- .github/workflows/e2e-kind-upgrades.yaml
- .github/workflows/e2e-kind-upgradessha256.yaml
- .github/workflows/e2e-kind-versionchecker.yaml
- .github/workflows/nightly-smoketest.yaml
- .github/workflows/templates.yaml
- .github/workflows/tests.yaml
- .github/workflows/update-crdb-versions.yaml
- CHANGELOG.md
Rather than upgrading all of the `4.0.0` values in our workflows, I
think we should leverage [bazelisk] for this. This will ensure we've
always got the latest official release being used in CI.
If we ever wanted to fix a version we can always use the env or rcfile
options supported by bazelisk (not used here).
**Checklist**
[bazelisk]: https://github.com/bazelbuild/bazelisk
> Use bazelisk in CI to avoid hard coded bazel versions

- CHANGELOG.md
- cmd/cockroach-operator/main.go
As mentioned in #863, there is no longer a default value for
`LeaderElectionID` on the manager options. This means that when
`--enable-leader-election` is supplied, the operator fails to start.
I've supplied a default value for the flag here, since most cases won't
need to change this. However, if you intend on running multiple versions
of the operator, having the CLI flag makes it easy to avoid name
collisions.
Fixes #863
**Checklist**
> Enable support for leader election.

- e2e/e2e.go
We continue to experience timeouts when running GKE nightlies. The
errors are timeouts, particularly in the upgrade e2e test. I don't see
anything obvious in the code, nor any meaningful changes from when they
worked to fix. So I've doubled the timeout from 10m to 20m.
If this works, as in, it provides the necessary amount of time, we can
tighten it over time.
> Bump e2e cluster creation timeout to 20m

- CHANGELOG.md
- e2e/create/create_test.go
- pkg/resource/cluster.go
- pkg/resource/job.go
- pkg/resource/statefulset.go
- pkg/testutil/builder.go
This patch fixes several accesses to
`spec.Image` fields that did not check
for potential `nil` value.
This bug eluded e2e tests because
the `Image` field was always set to
non-nil. A knob to the test cluster
builder is added so that we can properly
test.
> fix NPE error when accessing spec.Image

- CHANGELOG.md
- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/rbac/role.yaml
- config/samples/crdb-tls-example.yaml
- crdb-versions.yaml
- e2e/decommission/decommission_test.go
- examples/client-secure-operator.yaml
- examples/example.yaml
- examples/smoketest.yaml
- install/operator.yaml
- pkg/controller/cluster_controller.go
Previously, full cluster restarts were not working due to the operator
not having permissions. This PR grants the correct permissions.
Addresses issue #881.
> Fix support for full cluster restarts

- apis/v1alpha1/cluster_types.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- install/crds.yaml
- pkg/resource/cluster.go
Previously, custom logging configs were now allowed, but there was not a
lot of documentation and error checking. This PR adds this.
> Add error checking and comments around custom logging config.

- CHANGELOG.md
- e2e/decommission/decommission_test.go
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
- pkg/testutil/require.go
Currently we have the termination grace period set to 1m. This seems a
bit low since we need to do a number of things (e.g. drain connections)
before properly shutting down and it could take a bit longer on busy clusters.
I've bumped this to 5m to give the nodes a little more time. This
represents an upperbound of the time, so should have no speed/perf
penalty in most cases.
**Checklist**
> Increase TerminationGracePeriod to 5m

- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args_with_join.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args_with_join_in.yaml
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
We have been observing a slight issue with the currently default behavior of automatically including the `--join` flag for all the nodes within the StatefulSet. For most cases this works great, however, when we want to make the pods join a different set of nodes and we explicitly pass in the `--join` flag as a part of `additionalArgs` field, we have observed that the pods of the new cluster will still end up happy forming their own quorum even if they are temporarily not able to reach the nodes specified explicitly in the `--join` command that the we passed.
Ideally we'd like it to respect and prefer the `--join` command passed within the `additionalArgs` over the default. If there are reachability issues with the existing nodes then I think it's okay for those to be surfaced explicitly …
> Prefer user added --join flags over default when explicitly passed

- pkg/resource/BUILD.bazel
- pkg/resource/cluster.go
- pkg/resource/cluster_test.go
- pkg/testutil/builder.go
We had been seeing issues where the Operator fails to establish DB connection to the cluster when using custom Node and Client TLS certificates. On a closer examination it looked like they were always referencing hardcoded secret names, which were absent when using custom secrets that were passed to the `CrdbCluster` as inputs to `nodeTLSSecret` and `clientTLSSecret`.
> resource/cluster: prefer custom node-tls or client-tls secrets

- CHANGELOG.md
- pkg/controller/BUILD.bazel
- pkg/controller/cluster_controller.go
- pkg/resource/cluster.go
Previously, Status updates could fail due to version conflicts. This
commit pulls all status update logic into a helper function that
utilizes retry.RetryOnConflict to ensure that .Status updates get
persisted in spite of resource version changes.
Additionally, this commit removes an early bailout if the controller
detects a divergence in the currently loaded resource and the API
version. This change should have no notable affects as it took place
after any actors ran.
It also fixes a buglet that overwrote the reconcilers context,
negating the maximum runtime for a single reconcilation loop.
**Checklist**
> controller: consolidate status update logic

- CHANGELOG.md
- apis/v1alpha1/cluster_types.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- e2e/upgrades/upgrades_test.go
- install/crds.yaml
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/automount_sa.golden
- pkg/resource/testdata/TestStatefulSetBuilder/automount_sa_in.yaml
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args_with_join.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
- pkg/testutil/builder.go
In #107 auto-mounting of the default service account token was disabled.
Presumably this was because it wasn't necessary in order to run
Cockroach.
We've had a number of users request the ability to re-enable this as
it's the default behaviour in Kubernetes and is often used to grant
access to other systems through IAM grants (e.g. backups in S3).
This PR adds an `AutomountServiceAccountToken` field to the cluster spec.
When set, the service account token will be mounted. By default
this value is `false` for backward compatibility reasons.
**Checklist**
> Allow option to auto-mount service account token

- Makefile
- hack/bin/deps.bzl
Previously, buckets holding kubetest binaries were problematic so a new
one was created. Since these new binaries were built with go 1.19, PATH
entries must also be absolute:
https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/os/exec/lp_unix.go;l=60
**Checklist**
> Fix e2e tests

- CHANGELOG.md
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/automount_sa.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
Installing certs with permission 700 was causing issues when querying CRDB. This PR fixes it by changing it to 600.
**Checklist**
> Fix cert permissions

- cmd/cockroach-operator/prep_webhooks.go
- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/samples/crdb-tls-example.yaml
- crdb-versions.yaml
- e2e/kubetest2-openshift/deployer/up.go
- e2e/openshift/openshift_packaging_test.go
- examples/client-secure-operator.yaml
- examples/example.yaml
- examples/smoketest.yaml
- hack/bin/deps.bzl
- hack/crdbversions/main.go
- hack/release/main.go
- hack/release/steps.go
- hack/release/steps_test.go
- hack/update_crdb_versions/main.go
- install/operator.yaml
- pkg/actor/generate_cert.go
- pkg/actor/partitioned_update_test.go
- pkg/kube/dialer.go
- pkg/kuberecord/recorder.go
- pkg/resource/statefulset_test.go
- pkg/security/certs_test.go
- pkg/testutil/assert.go
- pkg/testutil/helpers.go
- pkg/testutil/validate_headers.go
- pkg/testutil/validate_headers_test.go
- pkg/util/tmp_dir.go
Making tests on master pass. Also regenerated the templates since that was missed when adding new CRDB versions.
**Checklist**
> Bump golangci-lint to v1.50.1 and update code as necessary

- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/samples/crdb-tls-example.yaml
- crdb-versions.yaml
- e2e/openshift/openshift_packaging_test.go
- examples/client-secure-operator.yaml
- examples/example.yaml
- examples/smoketest.yaml
- hack/bin/deps.bzl
- hack/update_crdb_versions/main_test.go
- install/operator.yaml
golangci-lint version is updated from the 1.50.1 because it is hitting the OOM issue with the Go 1.20 version and its fix has been done in 1.51.1.
> Update the golangci-lint version from 1.50.1 to 1.51.1

- pkg/controller/cluster_controller.go
- pkg/resource/cluster.go
Fixes #951 
Currently, we are storing the CR in resource.Cluster object and changing this CR during the course of reconcile and at last call the update function. This causes the `object has been already modified, please apply your changes to the latest version and try again`
With this change, we take the copy of the object before reconcile, run the changes on our CR, then patch will take diff for the before and after of object to find only the changed fields. This patch operation is more safer in terms of updating the CR.
With this change, cluster is in correct state after crdb is provisioned:
> Fix the clusterStatus should reflect correct state of cluster

- .gitignore
- Makefile
- build/release/teamcity-publish-openshift-bundle.sh
- build/release/teamcity-publish-openshift.sh
- build/release/teamcity-publish-release.sh
- build/release/teamcity-support.sh
- config/default/BUILD.bazel
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
- config/templates/csv.yaml.in
- hack/BUILD.bazel
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- hack/bundle.sh
- hack/redhat.sh
**Install preflight binary on Linux machines**
```
Adding preflight to the list of OpenShift binaries installed. For now,
this is only available on Linux machines and won't be added to anyone
using Darwin.
```
**Publish operator and bundle images for RedHat/OpenShift**
```
Updating the build/release scripts to handle publishing the bundle
images and running preflight on them.
The publish-openshift script downloads the tagged release from
DockerHub, retags it correctly for the RedHat scanning repo, pushes it,
and finally runs the preflight check on it.
The openshift-bundle script largely does the same, only it publishes the
bundle image rather than the operator image. The same script is used for
both the certified and marketplace bundles. Passing `MARKETPLACE=1` will
use the marketplace …
```
> Update Openshift Release Process

- hack/bin/deps.bzl
- hack/bundle.sh
- Changed the source file name from `opm` to `darwin-amd64-opm` as per change in the tar file.
- Removed deletion of webhook service from bundle which is required in bundle for webhook
> Update the bundle.sh to generate the bundle through opm

- CHANGELOG.md
- pkg/actor/validate_version.go
**Checklist**
Output with the fix if we add invalid value for `whenUnsatisfiable` under `topologySpreadConstraints`:
```
himanshu@crlMBP-TT9JHHY615MjIz ~ % kubectl get crdbcluster test-cluster -o yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
creationTimestamp: "2023-05-09T10:04:06Z"
generation: 1
name: test-cluster
namespace: default
resourceVersion: "3547286"
uid: c842fb07-2289-4634-acae-3db8067735ff
spec:
additionalLabels:
crdb: is-cool
dataStore:
pvc:
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 1Gi
volumeMode: Filesystem
image:
name: cockroachdb/cockroach:v21.2.10
nodes: 3
resources:
limits:
cpu: 2
memory: 2Gi
requests:
cpu: 100m
memory: 1Gi …
```
> fix error message if invalid value for topologySpreadConstraints flags passed

- CHANGELOG.md
- apis/v1alpha1/webhook.go
- apis/v1alpha1/webhook_test.go
K8s does not support mutating selectors and labels
on statefulsets at the same time:
https://github.com/kubernetes/kubernetes/issues/90519.
This PR adds a validation hook to reject
mutating additionalLabels, which will cause
mutating selectors and labels on the underlying sts,
and a constant reconciliation loop.
**Checklist**
> reject mutations to additionalLabels field

- build/release/teamcity-publish-openshift.sh
- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/samples/crdb-tls-example.yaml
- config/templates/csv.yaml.in
- crdb-versions.yaml
- examples/client-secure-operator.yaml
- examples/example.yaml
- examples/smoketest.yaml
- install/operator.yaml
- Added new quay.io registry to push image for redhat certification.
- Added a new RELATED_IMAGE_COCKROACH_OPERATOR env variable in CSV needed for redhat certification.
- Made sure the CSV we generate is in sync with it is generated by the operator-sdk
> Fix the jobs to release on openshift certification

- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/templates/csv.yaml.in
- hack/bundle.sh
Openshift certification needs some additional annotations which was not generated by `make release/generate-bundle`. I have added logic to generate those annotations so that the generated bundle passes certification in one attempt.
> Update CSV and metadata annotations for openshift certification

- hack/bin/deps.bzl
Need to upgrade preflight version to 1.9.1 as previous version 1.2.1 got deprecated.
> Upgrade preflight version from 1.2.1 to 1.9.1

- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- crdb-versions.yaml
- e2e/e2e.go
- e2e/versionchecker/versionchecker_test.go
- install/operator.yaml
- pkg/clustersql/settings.go
- pkg/clustersql/settings_test.go
`kv.snapshot_recovery.max_rate` cluster setting was removed. In newer versions it returns an error which blocks decommissioning. This will stub in a default value if the error is returned.
**Checklist**
> Adding a check and default huge value for deprecated cluster setting 

- pkg/resource/job.go
version checker job is getting OOM on openshift sometimes. The resource requests and limits are same for the version checker job which is not ideal. There should be some wiggle room if there is memory spike at some point, hence increased the resource limits for the version checker job.
> vcheck job resource limits should be greater than resource requests

- BUILD.bazel
- Makefile
- WORKSPACE
- cmd/cockroach-operator/BUILD.bazel
- cmd/cockroach-operator/linux-amd64/BUILD.bazel
- cmd/cockroach-operator/linux-arm64/BUILD.bazel
- config/manager/deployment.yaml
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- install/operator.yaml
- Add support for linux arm64 images.
- Upgrade cockroach binary from v21.2.0 to v22.2.19 as it has official support of arm64 image.
> Add Support for linux arm64 images

- BUILD.bazel
- WORKSPACE
- config/crd/BUILD.bazel
- config/default/BUILD.bazel
- config/default/apply_k8s.sh
- config/webhook/BUILD.bazel
- hack/dev.sh
Removed rules_k8s bazel dependency as it is deprecated and not supported with rules_oci
> Fix the development workflow in make dev/build.

- e2e/upgrades/upgrades_test.go
- pkg/update/internal.go
- pkg/update/update_cockroach_version.go
- pkg/update/update_cockroach_version_common.go
- pkg/update/update_cockroach_version_common_test.go
Fixes: #1088 
1. Allow Innovative upgrades to be skipped during upgrade process.
2. Added e2e tests to for the same.
> Allow Innovative upgrades to be skipped during upgrade

- CHANGELOG.md
- apis/v1alpha1/cluster_types.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- install/crds.yaml
- pkg/resource/job.go
- pkg/resource/statefulset.go
With this PR, users can specify the [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) for the pods:
```
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
name: cockroachdb
spec:
priorityClassName: "a-priority-class-name"
```
Addressing Issue https://github.com/cockroachdb/cockroach-operator/issues/1103.
**Checklist**
> Add priorityClassName as an optional configuration

- cmd/cockroach-operator/BUILD.bazel
- cmd/cockroach-operator/main.go
- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/samples/crdb-tls-example.yaml
- crdb-versions.yaml
- examples/client-secure-operator.yaml
- examples/example.yaml
- examples/smoketest.yaml
- install/operator.yaml
Attached screenshot with readable timestamp
> Add human readble timestamp format in operator logs

- pkg/actor/partitioned_update.go
- pkg/actor/partitioned_update_test.go
- pkg/controller/cluster_controller_test.go
- pkg/resource/statefulset.go
- pkg/update/BUILD.bazel
- pkg/update/update_cockroach_version.go
- pkg/update/update_cockroach_version_common.go
- pkg/update/update_cockroach_version_common_test.go
Issue: When upgrading CockroachDB clusters using FIPS-compliant images, the operator was performing a double rollout:
1. First rollout: Switching to a non-FIPS version of the target image
2. Second rollout: Correcting back to the proper FIPS version
RCA:
The issue was caused by inappropriate image manipulation in two key locations:
1. `partitioned_update.go`: `getImageNameNoVersion` function stripped version tags from Docker images. For tagged FIPS images like `cockroachdb/cockroach:v25.2.1-fips`, it would strip everything after the colon, losing the FIPS designation.
2. `update_cockroach_version.go`: When `getImageNameNoVersion()` stripped the FIPS tag, this logic would reconstruct the image as cockroachdb/cockroach:v25.2.1 (standard image) instead of preserving the original …
> Fix cockroachdb version upgrade with fips image
