- hack/common.sh
The error message should be for kustomize and not kubectl.
> Fixing copy paste error

- Makefile
- README.md
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- config/examples/3-nodes-secure-kube-cert-v20.1.yaml
- config/examples/example.yaml
- config/rbac/role.yaml
- deploy/operator.yaml
- hack/apply-crdb-example.sh
- hack/apply-operator.sh
- hack/common.sh
- hack/create-gke-cluster.sh
- hack/delete-crdb-example.sh
- hack/delete-gke-cluster.sh
- hack/delete-operator.sh
- hack/functions.sh
- hack/make.sh
- hack/push-operator-gcr.sh
- hack/update-crd-manifest-headers.sh
- hack/update-header.sh
- hack/verify_boilerplate.py
Work getting `make lint` happy and working.
I did not fix all the problems with spellcheck since some are nontrial to fix, and not critical to the operator.  I disabled a couple of checks.  The Dockerfiles are not linted yet and I will add and issue.
> Work on linting fixes

- Dockerfile.test-runner
- Makefile
- hack/update-header.sh
- running bash as the default shell, so I had to add bash to update test-runner container
- added variable for the e2e tests, that can allow a single test to run
- found a couple of listing errors
> Makefile Improvements

- Makefile
Removing a couple of linters till we need them
> Updating Linting

- pkg/actor/actor.go
- pkg/actor/deploy.go
- pkg/actor/initialize.go
- pkg/actor/request_cert.go
- pkg/actor/upgrade.go
- pkg/controller/cluster_controller.go
- pkg/resource/resource.go
Code commenting for the most important logic. Let me know if something needs to be expanded.
Closes #118
> Initial set of code comments

- BUILD.bazel
- cmd/cockroach-operator/BUILD.bazel
- go.mod
- go.sum
- hack/BUILD.bazel
- hack/build/repos.bzl
- hack/update-deps.sh
- pkg/update/BUILD.bazel
- pkg/update/internal.go
- pkg/update/oss_update_cockroach_version.go
- pkg/update/update.go
- pkg/update/update_cockroach_version.go
- pkg/update/update_cockroach_version_common.go
Looks like some extra go.mod changes snuck in? Uncertain if that's a problem
> Add update code

- e2e/e2e_test.go
This should create the problem that I see in https://github.com/cockroachdb/cockroach-operator/issues/187
I am not certain if this is a kind issue or a problem with the operator.  I am guessing that it is an issue with kind and or our e2e testing.
> New e2e test for CR v20.1.6

- Makefile
> Creating Alpha 2

- DEVELOPER.md
Adding instructions for accessing the admin UI.
> dev docs updates

- examples/example.yaml
changed cockroachdb tag to 20.2.0
> update example.yaml to point at 20.2.0

- cmd/cockroach-operator/BUILD.bazel
- hack/build/print-workspace-status.sh
I turned on stamping and that allows us to use ENV variables
to set to of the labels. I also updated some of the capitalization
in some of the english in the other labels.
> Fixing stamping in container

- api/v1alpha1/cluster_types.go
- bundle/manifests/cockroach-operator.clusterserviceversion.yaml
- bundle/manifests/crdb.cockroachlabs.com_crdbclusters.yaml
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- deploy/certified-metadata-bundle/cockroach-operator/1.1.0/cockroach-operator.v1.1.0.clusterserviceversion.yaml
- deploy/certified-metadata-bundle/cockroach-operator/1.1.0/crdb.cockroachlabs.com_crdbclusters.yaml
- deploy/certified-metadata-bundle/cockroach-operator/1.1.0/manifests/cockroach-operator.v1.1.0.clusterserviceversion.yaml
- deploy/certified-metadata-bundle/cockroach-operator/1.1.0/manifests/crdb.cockroachlabs.com_crdbclusters.yaml
- deploy/certified-metadata-bundle/cockroach-operator/latest/cockroach-operator.v1.1.0.clusterserviceversion.yaml
- deploy/certified-metadata-bundle/cockroach-operator/latest/crdb.cockroachlabs.com_crdbclusters.yaml
- deploy/certified-metadata-bundle/cockroach-operator/latest/manifests/cockroach-operator.v1.1.0.clusterserviceversion.yaml
- deploy/certified-metadata-bundle/cockroach-operator/latest/manifests/crdb.cockroachlabs.com_crdbclusters.yaml
- hack/BUILD.bazel
- fix https://github.com/cockroachdb/cockroach-operator/issues/137
- regenerate crd and csv for OpenShift with the fix
> fix minAvailable typo for  PDB issue

- README.md
Fixes https://github.com/cockroachdb/docs/issues/9461.
> fix example.yaml link

- apis/v1alpha1/cluster_defaults.go
- apis/v1alpha1/cluster_defaults_test.go
- apis/v1alpha1/cluster_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- pkg/actor/initialize.go
- pkg/resource/discovery_service.go
- pkg/resource/discovery_service_test.go
- pkg/resource/public_service.go
- pkg/resource/public_service_test.go
- pkg/resource/resource_test.go
- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_insecure_statefulset_in.yaml
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure_in.yaml
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_cli_args_in.yaml
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources.golden
- pkg/resource/testdata/TestStatefulSetBuilder/insecure_statefulset_with_resources_in.yaml
- adding new API value SQLPort
- setting default SQLPort and moving default GRPCPort
- fixing unit tests
- updating start parameters for database
> Moving to 3 port database configuration

- e2e/assert.go
- pkg/actor/decommission.go
- pkg/actor/partitioned_update.go
Need to use the SQL Port instead of the GRPC Port to connect
to the database now.
> Fixing missed SQL Ports

- .gitignore
- Makefile
- hack/BUILD.bazel
- hack/bin/BUILD.bazel
- hack/bin/deps.bzl
- hack/k8s/BUILD.bazel
- hack/k8s/verify_k8s_running.go
- pkg/resource/cluster.go
- cleaning up Makefile
- downloading tester-exec
- added script to test if GKE has started
- above script needs to be replaced by go code, and work
for both GKE and kind
- get kind and gke working in same pattern
> More work on getting integration testing working

- Makefile
- e2e/e2e_test.go
- go.mod
- hack/k8s/verify_k8s_running.go
- pkg/testutil/validate_headers.go
1. Removed old or targets we should not use
2. added a bunch of documentation on the e2e targets
3. moved a couple of targets around
1. increased timeout on verify program
2. got pvc testing running on GKE
> Cleaning up Makefile and adding documentation

- config/samples/crdb-tls-example.yaml
adding cockroachDBVersion to the OpenShift example. @rail can you please add updating this file to the release process?
> adding cockroachDBVersion to the OpenShift example

- hack/bin/deps.bzl
Use openshift 4.7.9 and pin that version
> Pin openshift client to 4.7.9

- examples/example.yaml
> uncomment resources, update image

- Makefile
I think the target got messed up, so I am adding it back in.
> Adding Makefile target to run openshift e2e

- pkg/actor/BUILD.bazel
- pkg/actor/generate_cert.go
We are getting an exception that we do not have the latest CRD version
so we need to try to update it again.
> Retry updating the CRD

- pkg/actor/validate_version.go
- pkg/resource/job.go
We are getting a nil when we get the Job from the API.  This code
runs a list, which reconciles the API, and gets the selector.
> Fixing nil on Job selector

- pkg/actor/validate_version.go
Added another check and added some logging.
> Adding logging and cleaning up code

- apis/v1alpha1/cluster_types.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- pkg/actor/deploy.go
- pkg/actor/resize_pvc.go
- pkg/actor/validate_version.go
- pkg/labels/label.go
- pkg/labels/label_test.go
- pkg/resource/discovery_service_test.go
- pkg/resource/pod_distruption_budget.go
- pkg/resource/pod_distruption_budget_test.go
- pkg/resource/public_service_test.go
- pkg/resource/resource_test.go
- pkg/resource/statefulset_test.go
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure_in.yaml
- pkg/testutil/builder.go
- pkg/testutil/require.go
- Adding new API field 'AdditionalLabels' - 'additionalLabels in YAML
- Updating copy and create for handling labels
- Added unit testing
> Adding capability to have custom labels

- config/templates/example.yaml.in
- examples/example.yaml
- updated the example.yaml.in file with the map additionalLabels
> Adding example for AdditionalLabels

- e2e/create/create_test.go
- pkg/testutil/require.go
- added new e2e test to create an insecure cluster
- using v21.1.6
> Adding e2e test for insecure cluster

- README.md
> Add OpenShift nightly badge

- examples/client-secure-operator.yaml
> remove labels on client pod

- pkg/actor/generate_cert.go
- pkg/actor/partitioned_update.go
- pkg/resource/cluster.go
- pkg/resource/statefulset.go
- pkg/security/certs.go
- pkg/security/certs_test.go
- pkg/testutil/fake.go
- pkg/testutil/require.go
- pkg/update/BUILD.bazel
- pkg/update/update.go
- pkg/update/update_cockroach_version.go
Removing some unused code from `pkg/...`. I found these by using `staticcheck -check U1000 ./pkg/...`.
> Remove unused code

- pkg/resource/webhook_secret.go
Just removing some left over cruft from the webhook secret.
> Remove unused SecretInterface reference

- pkg/resource/discovery_service.go
> rm extraneous fmt.Println

- apis/v1alpha1/action_types.go
- pkg/actor/actor.go
- pkg/actor/actor_test.go
- pkg/actor/partitioned_update.go
as noted at https://docs.google.com/document/d/1b46djy1DJ2XEGS-tvLx9mw69n00srNB05a8NroLo_V4/edit?disco=AAAAPPFe5Pk
> rename PartialUpdate to PartitionedUpdate

- Makefile
- PROJECT
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- hack/BUILD.bazel
- hack/opm-build-bundle.sh
- hack/update-pkg-manifest.sh
We use two main scripts for packaging up the bundle; update-pkg-manifest.sh and opm-build-bundle.sh. The former generates the CSV and CRD files in deploy/.../<version>, while the later generates a bundle and updates the latest release info.
I found these scripts, as they were written, a little hard to grok. So I updated them to use smaller, well-named functions that state what the goal is and hopefully make the process a little easier to follow for others as well.
I wanted to make sure that nothing unexpected changed here. I started by moving the current release to a local directory (for later comparison) and generating a new bundle.
* `mv deploy/certified-metadata-bundle/cockroach-operator/2.1.0 prev`
* `make release/opm-build-bundle` (now depends on `release/update-pkg-manifest`)
I then …
> Refactor packaging scripts

- bundle.Dockerfile
- bundle/manifests/cockroach-operator.clusterserviceversion.yaml
- bundle/manifests/crdb.cockroachlabs.com_crdbclusters.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
#756 got merged before I had a chance to address @udnay's comment about updating the bundle directory.
This diff was made by running `make gen-csv`.
**Checklist**
> Run make gen-csv to update bundle directory

- CHANGELOG.md
- apis/v1alpha1/cluster_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/crdb.cockroachlabs.com_crdbclusters.yaml
- config/templates/example.yaml.in
- examples/example.yaml
- install/crds.yaml
- pkg/resource/statefulset.go
Added support for nodeSelectors to the CRD.
Resolves #762
> Added nodeSelector support

- CHANGELOG.md
- pkg/resource/job.go
Added resource requirements for vcheck container.
Resolves #796
> Add resource requirements for vcheck container

- .github/workflows/update-crdb-versions.yaml
The action we used before was not flexible enough to tweak all properties we need to have PRs with CLA signed.
> ci: fix automatic update issues

- config/manager/patches/image.yaml
- config/manifests/bases/cockroach-operator.clusterserviceversion.yaml
- config/manifests/patches/deployment_patch.yaml
- config/rbac/role.yaml
- crdb-versions.yaml
- install/operator.yaml
> Fix the auto prune PVC feature gate enabled

- pkg/resource/statefulset.go
- pkg/resource/testdata/TestStatefulSetBuilder/automount_sa.golden
- pkg/resource/testdata/TestStatefulSetBuilder/default_secure.golden
Add Quality of Service for init containers of statefulset.
> Add QoS for the init containers

- README.md
This PR just fixes https://github.com/cockroachdb/cockroach-operator/issues/1015 
**Checklist**
> update readme with correct file location
